# Use this workflow to initialize your repository with the fimware you need for your keyboard
# if you have multiple keyboards, you need to have 1 copy of this file per keyboard
# rename the name below so that you can see the different keyboards in your github actions
name: initialize

# You will need to manually trigger this workflow
on:  ['workflow_dispatch']

jobs:
  initialize-firmware:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
      max-parallel: 1  
      matrix:
        # Replace the following with the keyboard you want to setup.  
        # Only 1 keyboard is supported.  For more keyboards, copy and rename this file.
        keyboard: ['breadboard-promicro']
        # Keymap of the keyboard to setup.  Multiple keymaps can be setup following this example: ['default','jpconstantineau']
        keymap: ['test_keymap']
        # keyboard configuration. Multiple configs can be setup following this example: ['left','right']
        keyboard_config: ['single']
        # hardware configuration. must have both components of the path in the BlueMicro_BLE keyboard examples path
        hardware_config: ['pca10056/bluemicro840v1_0']
        # Available options
        # feather_nrf52832 - use this for most nRF52832 based boards (needs Arduino_nRF52_Bootloader)
        # bluemicro_nrf52840
        # bluemacro_nrf52840
        # nice_nano
        # pca10056 - use this for all other nRF52840 based boards not listed above (needs Arduino_nRF52_Bootloader)
        compile_with: ['bluemicro_nrf52840']
        # this parameter controls the generation of a yml file you can copy to the .github/workflows folder to build the uf2.
        # uf2 generation is only usesul for nrf52840 boards.  nrf52832 controllers do not support uf2 uploading.
        setup_build_yml: ['false']

    # you shouldn't need to edit anything below
    steps:
      - name: checkout builder repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
      - name: update from last run
        run: git pull
      - name: clone BlueMicro_BLE repository
        run: |
          git clone https://github.com/jpconstantineau/BlueMicro_BLE.git
      - name: create firmware folder
        run: |
          mkdir ${{ matrix.keyboard }}-${{ matrix.keymap }}-${{ matrix.keyboard_config }}-${{ matrix.compile_with }}
      - name: copy main firmware files
        run: |
          cp BlueMicro_BLE/firmware/*.cpp ${{ matrix.keyboard }}-${{ matrix.keymap }}-${{ matrix.keyboard_config }}-${{ matrix.compile_with }}
          cp BlueMicro_BLE/firmware/*.h ${{ matrix.keyboard }}-${{ matrix.keymap }}-${{ matrix.keyboard_config }}-${{ matrix.compile_with }}
          cp BlueMicro_BLE/firmware/firmware.ino ${{ matrix.keyboard }}-${{ matrix.keymap }}-${{ matrix.keyboard_config }}-${{ matrix.compile_with }}/${{ matrix.keyboard }}-${{ matrix.keymap }}-${{ matrix.keyboard_config }}-${{ matrix.compile_with }}.ino
      - name: copy board specific files
        run: |
          cp BlueMicro_BLE/firmware/keyboards/${{ matrix.keyboard }}/config/${{ matrix.keyboard_config }}/keyboard_config.h ${{ matrix.keyboard }}-${{ matrix.keymap }}-${{ matrix.keyboard_config }}-${{ matrix.compile_with }}
          cp BlueMicro_BLE/firmware/keyboards/${{ matrix.keyboard }}/hardware/${{ matrix.hardware_config }}/hardware_config.h ${{ matrix.keyboard }}-${{ matrix.keymap }}-${{ matrix.keyboard_config }}-${{ matrix.compile_with }}
          cp BlueMicro_BLE/firmware/keyboards/${{ matrix.keyboard }}/keymaps/${{ matrix.keymap }}/keymap.h ${{ matrix.keyboard }}-${{ matrix.keymap }}-${{ matrix.keyboard_config }}-${{ matrix.compile_with }}
          cp BlueMicro_BLE/firmware/keyboards/${{ matrix.keyboard }}/keymaps/${{ matrix.keymap }}/keymap.cpp ${{ matrix.keyboard }}-${{ matrix.keymap }}-${{ matrix.keyboard_config }}-${{ matrix.compile_with }} 
      - name: create build workflow
        if: ${{ matrix.setup_build_yml }}
        run: |
          cp .github/workflow-templates/build.yml build-${{ matrix.keyboard }}-${{ matrix.keymap }}-${{ matrix.keyboard_config }}-${{ matrix.compile_with }}.yml
          sed -i 's/ReplaceMeWithSketchName/${{ matrix.keyboard }}-${{ matrix.keymap }}-${{ matrix.keyboard_config }}-${{ matrix.compile_with }}/' build-${{ matrix.keyboard }}-${{ matrix.keymap }}-${{ matrix.keyboard_config }}-${{ matrix.compile_with }}.yml
          sed -i 's/ReplaceMeWithCompileWith/${{ matrix.compile_with }}/' build-${{ matrix.keyboard }}-${{ matrix.keymap }}-${{ matrix.keyboard_config }}-${{ matrix.compile_with }}.yml
          ls -l ${{ matrix.keyboard }}-${{ matrix.keymap }}-${{ matrix.keyboard_config }}-${{ matrix.compile_with }}
          git add build-${{ matrix.keyboard }}-${{ matrix.keymap }}-${{ matrix.keyboard_config }}-${{ matrix.compile_with }}.yml
      - name: remove BlueMicro_BLE repository
        run: |
          rm -r BlueMicro_BLE
      - name: check back in the changes to this repo
        run: |
          ls -l
          git config --global user.name 'gh-actions'
          git config --global user.email 'gh-actions@noreply.github.com'
          git add ${{ matrix.keyboard }}-${{ matrix.keymap }}-${{ matrix.keyboard_config }}-${{ matrix.compile_with }}
          git commit -m "Initialized ${{ matrix.keyboard }}-${{ matrix.keymap }}-${{ matrix.keyboard_config }} using GitHub Actions"
          git push
